"""Metal AST Node definitions"""

from ..common_ast import (
    ArrayAccessNode,
    AssignmentNode,
    ASTNode,
    AttributeNode,
    BinaryOpNode,
    BreakNode,
    CallNode,
    CaseNode,
    CastNode,
    ConstantBufferNode,
    ContinueNode,
    DeleteNode,
    DesignatedInitializerNode,
    DiscardNode,
    DoWhileNode,
    EnumNode,
    ForNode,
    FunctionCallNode,
    FunctionNode,
    IfNode,
    InitializerListNode,
    MemberAccessNode,
    MethodCallNode,
    NewNode,
    PostfixOpNode,
    PreprocessorNode,
    RangeForNode,
    ReturnNode,
    ShaderNode,
    StaticAssertNode,
    StructNode,
    SwitchNode,
    SyncNode,
    TernaryOpNode,
    TextureSampleNode,
    ThreadgroupSyncNode,
    TypeAliasNode,
    UnaryOpNode,
    VariableNode,
    VectorConstructorNode,
    WhileNode,
)


class BlockNode(ASTNode):
    """Metal standalone scoped block."""

    def __init__(self, statements):
        self.statements = statements

    def __repr__(self):
        return f"BlockNode(statements={len(self.statements)})"


_COMMON_NODES = (
    ASTNode,
    ArrayAccessNode,
    AssignmentNode,
    AttributeNode,
    BinaryOpNode,
    BlockNode,
    BreakNode,
    CallNode,
    CaseNode,
    CastNode,
    ConstantBufferNode,
    ContinueNode,
    DeleteNode,
    DesignatedInitializerNode,
    DiscardNode,
    DoWhileNode,
    EnumNode,
    ForNode,
    FunctionCallNode,
    FunctionNode,
    IfNode,
    InitializerListNode,
    MemberAccessNode,
    MethodCallNode,
    NewNode,
    PostfixOpNode,
    PreprocessorNode,
    RangeForNode,
    ReturnNode,
    ShaderNode,
    StaticAssertNode,
    StructNode,
    SwitchNode,
    SyncNode,
    TernaryOpNode,
    TextureSampleNode,
    ThreadgroupSyncNode,
    TypeAliasNode,
    UnaryOpNode,
    VariableNode,
    VectorConstructorNode,
    WhileNode,
)
