import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest

import crosstl
import crosstl.translator.codegen as codegen
from crosstl.formatter import format_shader_code
from crosstl.translator.codegen.wgsl_codegen import WGSLCodeGen
from crosstl.translator.lexer import Lexer
from crosstl.translator.parser import Parser

WGSL_SHADER = """
shader WGSLSmoke {
    struct VSInput {
        vec3 position @ POSITION;
        vec2 uv @ TEXCOORD0;
    };
    struct VSOutput {
        vec4 position @ gl_Position;
        vec2 uv @ TEXCOORD0;
    };
    vertex {
        VSOutput main(VSInput input) {
            VSOutput output;
            output.position = vec4(input.position, 1.0);
            output.uv = input.uv;
            return output;
        }
    }
    fragment {
        vec4 main(VSOutput input) @ gl_FragColor {
            return vec4(input.uv, 0.0, 1.0);
        }
    }
}
"""

WGSL_COMPUTE_SHADER = """
shader WGSLCompute {
    compute {
        layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
        void main() {
            return;
        }
    }
}
"""


def parse_shader(source):
    return Parser(Lexer(source).get_tokens()).parse()


def project_root():
    return Path(__file__).resolve().parents[3]


def validate_wgsl_with_naga(tmp_path, code):
    naga = shutil.which("naga")
    if naga is None:
        pytest.skip("naga is not installed")
    source = tmp_path / "shader.wgsl"
    source.write_text(code, encoding="utf-8")
    result = subprocess.run(
        [naga, str(source)],
        capture_output=True,
        text=True,
        timeout=60,
    )
    diagnostics = "\n".join(
        part for part in (result.stdout, result.stderr) if part.strip()
    )
    assert result.returncode == 0, diagnostics


def test_wgsl_backend_is_target_only():
    spec = codegen.get_backend("webgpu")

    assert spec is not None
    assert spec.name == "wgsl"
    assert spec.source_registry_name is None
    assert "wgsl" not in codegen.source_backend_names()
    assert codegen.normalize_backend_name("shader.wgsl") == "wgsl"
    assert codegen.get_backend_extension("webgpu") == ".wgsl"
    assert isinstance(codegen.get_codegen("wgsl"), WGSLCodeGen)


def test_wgsl_codegen_emits_vertex_and_fragment_entry_points():
    generated = WGSLCodeGen().generate(parse_shader(WGSL_SHADER))

    assert generated.startswith("// Generated by CrossGL for WebGPU WGSL\n")
    assert "struct VSInput" in generated
    assert "@location(0) position: vec3<f32>," in generated
    assert "@location(2) uv: vec2<f32>," in generated
    assert "@builtin(position) position: vec4<f32>," in generated
    assert "@vertex\nfn vertex_main(input: VSInput) -> VSOutput" in generated
    assert (
        "@fragment\nfn fragment_main(input: VSOutput) -> @location(0) vec4<f32>"
        in generated
    )
    assert "vec4<f32>(input.position, 1.0)" in generated
    assert "return vec4<f32>(input.uv, 0.0, 1.0);" in generated


def test_wgsl_codegen_narrows_vec4_assignment_to_vec3_with_swizzle():
    shader = """
    shader WGSLVectorNarrowAssignment {
        cbuffer Uniforms {
            mat4 matModel;
        };
        struct VSInput {
            vec3 vertexPosition @ POSITION;
        };
        struct VSOutput {
            vec4 position @ gl_Position;
            vec3 fragPosition @ TEXCOORD0;
        };
        vertex {
            VSOutput main(VSInput input) {
                VSOutput output;
                output.position = vec4(input.vertexPosition, 1.0);
                output.fragPosition = matModel * vec4(input.vertexPosition, 1.0);
                return output;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "output.fragPosition = "
        "(_Uniforms.matModel * vec4<f32>(input.vertexPosition, 1.0)).xyz;"
        in generated
    )
    assert "vec3<f32>((_Uniforms.matModel *" not in generated


def test_wgsl_codegen_narrows_vec4_constructor_argument_to_vec3_swizzle():
    shader = """
    shader WGSLVectorNarrowConstructor {
        vertex {
            vec4 main(vec4 position @ POSITION) @ gl_Position {
                vec3 implicit = vec3(position);
                vec3 typed = vec3<f32>(position);
                return vec4(implicit + typed, position.w);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var implicit: vec3<f32> = position.xyz;" in generated
    assert "var typed: vec3<f32> = position.xyz;" in generated
    assert "vec3<f32>(position)" not in generated


def test_wgsl_codegen_preserves_explicit_io_attributes():
    shader = """
    shader WGSLExplicitAttributes {
        struct FragmentInput {
            vec4 position @builtin(position);
            vec2 uv @location(3) @interpolate(flat);
        };
        fragment {
            vec4 main(FragmentInput input) @location(1) {
                return input.position;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@builtin(position) position: vec4<f32>," in generated
    assert "@location(3) @interpolate(flat) uv: vec2<f32>," in generated
    assert (
        "fn fragment_main(input: FragmentInput) -> @location(1) vec4<f32>" in generated
    )


def test_wgsl_codegen_assigns_locations_to_entry_struct_members(tmp_path):
    shader = """
    shader WGSLStructLocations {
        struct VertexInput {
            vec3 position;
            vec2 uv;
        };
        struct VertexOutput {
            vec4 position @ gl_Position;
            vec2 uv;
            vec4 tint;
        };
        struct FragmentOutput {
            vec4 color;
        };
        vertex {
            VertexOutput main(VertexInput input) {
                VertexOutput output;
                output.position = vec4(input.position, 1.0);
                output.uv = input.uv;
                output.tint = vec4(input.uv, 0.0, 1.0);
                return output;
            }
        }
        fragment {
            FragmentOutput main(VertexOutput input) {
                FragmentOutput output;
                output.color = input.tint;
                return output;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@location(0) position: vec3<f32>," in generated
    assert "@location(1) uv: vec2<f32>," in generated
    assert "@builtin(position) position: vec4<f32>," in generated
    assert "@location(0) uv: vec2<f32>," in generated
    assert "@location(1) tint: vec4<f32>," in generated
    assert "@location(0) color: vec4<f32>," in generated
    validate_wgsl_with_naga(tmp_path, generated)


def test_wgsl_codegen_maps_derivative_intrinsics():
    shader = """
    shader WGSLDerivatives {
        fragment {
            vec4 main(vec3 frag_pos @ TEXCOORD0) @ gl_FragColor {
                vec3 dx = dFdx(frag_pos);
                vec3 dy = ddy(frag_pos);
                vec3 fine = ddx_fine(frag_pos);
                vec3 coarse = dFdyCoarse(frag_pos);
                return vec4(dx + dy + fine + coarse, 1.0);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "dpdx(frag_pos)" in generated
    assert "dpdy(frag_pos)" in generated
    assert "dpdxFine(frag_pos)" in generated
    assert "dpdyCoarse(frag_pos)" in generated
    assert "dFdx(" not in generated
    assert "ddy(" not in generated
    assert "ddx_fine(" not in generated
    assert "dFdyCoarse(" not in generated


def test_wgsl_codegen_emits_compute_workgroup_size():
    generated = WGSLCodeGen().generate(parse_shader(WGSL_COMPUTE_SHADER))

    assert "@compute" in generated
    assert "@workgroup_size(8, 4, 1)" in generated
    assert "fn compute_main()" in generated


def test_wgsl_codegen_emits_compute_builtin_parameter():
    shader = """
    shader WGSLComputeBuiltin {
        compute {
            layout(local_size_x = 4) in;
            void main(uint3 gid @ gl_GlobalInvocationID) {
                barrier();
                uint lane = gid.x;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@workgroup_size(4, 1, 1)" in generated
    assert "fn compute_main(@builtin(global_invocation_id) gid: vec3<u32>)" in generated
    assert "workgroupBarrier();" in generated
    assert "var lane: u32 = gid.x;" in generated


def test_wgsl_codegen_injects_direct_compute_builtin_references():
    shader = """
    shader WGSLDirectComputeBuiltin {
        compute {
            layout(local_size_x = 4) in;
            void main() {
                uint lane = gl_GlobalInvocationID.x;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "fn compute_main(@builtin(global_invocation_id) "
        "global_invocation_id: vec3<u32>)"
    ) in generated
    assert "var lane: u32 = global_invocation_id.x;" in generated


def test_wgsl_codegen_infers_untyped_compute_builtin_alias_locals():
    shader = """
    shader WGSLComputeBuiltinAliases {
        compute {
            void main() {
                let thread_id = gl_GlobalInvocationID;
                let block_id = gl_WorkGroupID;
                let thread_local_id = gl_LocalInvocationID;
                let block_dim = gl_WorkGroupSize;
                uint lane = thread_id.x + block_id.y + thread_local_id.z + block_dim.x;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var thread_id: vec3<u32> = global_invocation_id;" in generated
    assert "var block_id: vec3<u32> = workgroup_id;" in generated
    assert "var thread_local_id: vec3<u32> = local_invocation_id;" in generated
    assert "var block_dim: vec3<u32> = vec3<u32>(1u, 1u, 1u);" in generated
    assert ": void" not in generated


def test_wgsl_codegen_infers_void_placeholder_compute_builtin_alias_locals():
    shader = """
    shader WGSLComputeVoidAlias {
        compute {
            void main() {
                void thread_id = gl_GlobalInvocationID;
                uint lane = thread_id.x;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var thread_id: vec3<u32> = global_invocation_id;" in generated
    assert "var lane: u32 = thread_id.x;" in generated
    assert ": void" not in generated


def test_wgsl_codegen_infers_untyped_constructor_local_expression():
    shader = """
    shader WGSLUntypedConstructorLocal {
        fragment {
            vec4 main() @ gl_FragColor {
                let color = vec3(1.0, 0.5, 0.25);
                let alpha = 1.0;
                let boosted = alpha + 1.0;
                return vec4(color, boosted);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var color: vec3<f32> = vec3<f32>(1.0, 0.5, 0.25);" in generated
    assert "var alpha: f32 = 1.0;" in generated
    assert "var boosted: f32 = (alpha + 1.0);" in generated
    assert "return vec4<f32>(color, boosted);" in generated
    assert ": void" not in generated


def test_wgsl_codegen_injects_fragment_position_for_gl_fragcoord():
    shader = """
    shader WGSLFragmentPositionBuiltin {
        fragment {
            vec4 main() @ gl_FragColor {
                float xVal = gl_FragCoord.x;
                return vec4(xVal, gl_FragCoord.y, 0.0, 1.0);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "fn fragment_main(@builtin(position) position: vec4<f32>) "
        "-> @location(0) vec4<f32>"
    ) in generated
    assert "var xVal: f32 = position.x;" in generated
    assert "return vec4<f32>(xVal, position.y, 0.0, 1.0);" in generated
    assert "gl_FragCoord" not in generated


def test_wgsl_codegen_casts_unsigned_compute_builtin_component_to_signed_local():
    shader = """
    shader WGSLSignedComputeBuiltin {
        buffer float values[4];

        compute {
            layout(local_size_x = 4) in;
            void main() {
                int index = gl_GlobalInvocationID.x;
                values[index] = values[index] + 1.0;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "fn compute_main(@builtin(global_invocation_id) "
        "global_invocation_id: vec3<u32>)"
    ) in generated
    assert "var index: i32 = i32(global_invocation_id.x);" in generated
    assert "values[index] = (values[index] + 1.0);" in generated


def test_wgsl_codegen_treats_attribute_compute_functions_as_entry_points():
    shader = """
    shader WGSLAttributeComputeEntry {
        @compute
        @workgroup_size(2, 3, 4)
        void main() {
            uint lane = gl_GlobalInvocationID.x;
            uint3 block = gl_WorkGroupSize;
            return;
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@compute" in generated
    assert "@workgroup_size(2, 3, 4)" in generated
    assert (
        "fn compute_main(@builtin(global_invocation_id) "
        "global_invocation_id: vec3<u32>)"
    ) in generated
    assert "var lane: u32 = global_invocation_id.x;" in generated
    assert "var block: vec3<u32> = vec3<u32>(2u, 3u, 4u);" in generated


def test_wgsl_codegen_does_not_treat_semantic_attributes_as_stage_entries():
    shader = """
    shader WGSLSemanticAttributeFunction {
        vec4 main(vec4 pos @ Out_Position) @ Out_Color {
            return pos;
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "fn main(" in generated
    assert "@out_color" not in generated.lower()


def test_wgsl_codegen_strips_io_attributes_from_helper_parameters():
    shader = """
    shader WGSLHelperSemanticParameters {
        vec4 tint(vec4 color @ TEXCOORD0) {
            return color;
        }
        fragment {
            vec4 main(vec4 color @ TEXCOORD0) @ gl_FragColor {
                return tint(color);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "fn tint(color: vec4<f32>) -> vec4<f32>" in generated
    assert "fn tint(@location" not in generated
    assert (
        "@fragment\nfn fragment_main(@location(2) color: vec4<f32>) "
        "-> @location(0) vec4<f32>"
    ) in generated


def test_wgsl_codegen_emits_resource_address_spaces_and_bindings():
    shader = """
    shader WGSLResources {
        uniform vec4 tint;
        buffer float values[4];
        var<workgroup> scratch: float[4];
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar<uniform> tint: vec4<f32>;" in generated
    assert (
        "@group(0) @binding(1)\n" "var<storage, read_write> values: array<f32, 4>;"
    ) in generated
    assert "var<workgroup> scratch: array<f32, 4>;" in generated


def test_wgsl_codegen_preserves_explicit_set_and_binding_resources():
    shader = """
    shader WGSLExplicitResourceBindings {
        layout(set = 2, binding = 4) uniform sampler2D colorTex;
        sampler explicitSampler @set(3) @binding(5);
        layout(set = 4, binding = 6) uniform vec4 tint;
        layout(set = 5, binding = 7) buffer float values[4];
        cbuffer Registered : register(b8, space6) {
            float value;
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(2) @binding(4)\nvar colorTex: texture_2d<f32>;" in generated
    assert "@group(2) @binding(5)\nvar colorTex_sampler: sampler;" in generated
    assert "@group(3) @binding(5)\nvar explicitSampler: sampler;" in generated
    assert "@group(4) @binding(6)\nvar<uniform> tint: vec4<f32>;" in generated
    assert (
        "@group(5) @binding(7)\n" "var<storage, read_write> values: array<f32, 4>;"
    ) in generated
    assert "@group(6) @binding(8)\nvar<uniform> _Registered: Registered;" in generated


def test_wgsl_codegen_lowers_writeonly_uimage2d_to_storage_texture_store():
    shader = """
    shader WGSLStorageImage {
        uimage2D dstTexture @binding(2) @rgba32ui @writeonly;
        compute {
            void main() {
                imageStore(dstTexture, ivec2(1, 2), uvec4(3u, 4u, 5u, 6u));
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "@group(0) @binding(2)\n"
        "var dstTexture: texture_storage_2d<rgba32uint, write>;"
    ) in generated
    assert (
        "textureStore(dstTexture, vec2<i32>(1, 2), vec4<u32>(3, 4, 5, 6));" in generated
    )
    assert "imageStore" not in generated


def test_wgsl_codegen_infers_image2d_write_access_from_image_store():
    shader = """
    shader WGSLStorageImageInferredWrite {
        compute {
            layout(local_size_x = 1) in;
            uniform layout(rgba8) image2D outputImage;
            void main() {
                imageStore(outputImage, ivec2(1, 2), vec4(1.0));
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "@group(0) @binding(0)\n"
        "var outputImage: texture_storage_2d<rgba8unorm, write>;"
    ) in generated
    assert "textureStore(outputImage, vec2<i32>(1, 2), vec4<f32>(1.0));" in generated


def test_wgsl_codegen_infers_image2d_read_access_from_image_load():
    shader = """
    shader WGSLStorageImageInferredRead {
        compute {
            layout(local_size_x = 1) in;
            uniform layout(rgba32f) image2D inputImage;
            void main() {
                vec4 color = imageLoad(inputImage, ivec2(1, 2));
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "@group(0) @binding(0)\n"
        "var inputImage: texture_storage_2d<rgba32float, read>;"
    ) in generated
    assert (
        "var color: vec4<f32> = textureLoad(inputImage, vec2<i32>(1, 2));"
        in generated
    )
    assert "imageLoad" not in generated


def test_wgsl_codegen_rejects_storage_image_without_representable_format():
    shader = """
    shader WGSLStorageImageMissingFormat {
        uimage2D dstTexture @binding(2) @writeonly;
        compute {
            void main() {
                imageStore(dstTexture, ivec2(1, 2), uvec4(3u));
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target requires storage image resource dstTexture to declare "
            r"a representable image format such as layout\(rgba8\) or @rgba8"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_storage_image_without_access_metadata():
    shader = """
    shader WGSLStorageImageMissingAccess {
        image2D outputImage @binding(2) @rgba8;
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target requires storage image resource outputImage to declare "
            r"an access mode \(@readonly, @writeonly, or @readwrite\) or use it "
            r"in imageLoad/imageStore so access can be inferred"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_translates_complex_shader_storage_image_contract():
    shader = (project_root() / "examples/graphics/ComplexShader.cgl").read_text()

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "@group(0) @binding(9)\n"
        "var outputImage: texture_storage_2d<rgba8unorm, write>;"
    ) in generated
    assert "textureStore(outputImage, texCoord, color);" in generated


def test_wgsl_auto_bindings_skip_later_explicit_bindings():
    shader = """
    shader WGSLLateExplicitBindings {
        uniform vec4 autoTint;
        sampler2D explicitTexture @binding(0);
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar explicitTexture: texture_2d<f32>;" in generated
    assert "@group(0) @binding(1)\nvar explicitTexture_sampler: sampler;" in generated
    assert "@group(0) @binding(2)\nvar<uniform> autoTint: vec4<f32>;" in generated


def test_wgsl_synthetic_sampler_skips_occupied_binding():
    shader = """
    shader WGSLSyntheticSamplerCollision {
        sampler occupied @binding(1);
        sampler2D colorTex @binding(0);
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(1)\nvar occupied: sampler;" in generated
    assert "@group(0) @binding(0)\nvar colorTex: texture_2d<f32>;" in generated
    assert "@group(0) @binding(2)\nvar colorTex_sampler: sampler;" in generated


def test_wgsl_duplicate_explicit_resource_bindings_raise():
    shader = """
    shader WGSLDuplicateExplicitBindings {
        sampler firstSampler @binding(3);
        layout(set = 0, binding = 3) uniform vec4 tint;
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target resource binding collision: tint and firstSampler "
            r"both declare @group\(0\) @binding\(3\)"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_duplicate_hlsl_register_space_resource_bindings_raise():
    shader = """
    shader WGSLDuplicateRegisterBindings {
        cbuffer First : register(b2, space1) {
            float firstValue;
        };
        cbuffer Second : register(b2, space1) {
            float secondValue;
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target resource binding collision: Second and First "
            r"both declare @group\(1\) @binding\(2\)"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_hlsl_texture_and_sampler_registers_get_distinct_bindings():
    shader = """
    shader WGSLHLSLTextureSamplerRegisters {
        @register(t0)
        sampler2D g_texture;
        @register(s0)
        sampler g_sampler;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD) @ SV_TARGET {
                return texture(g_texture, g_sampler, uv);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar g_texture: texture_2d<f32>;" in generated
    assert "@group(0) @binding(1)\nvar g_sampler: sampler;" in generated
    assert "@group(0) @binding(2)\nvar g_texture_sampler: sampler;" in generated
    assert "return textureSample(g_texture, g_sampler, uv);" in generated


def test_wgsl_codegen_lowers_cbuffers_to_uniform_struct_bindings(tmp_path):
    shader = """
    shader WGSLCBuffer {
        cbuffer TestBuffer : register(b2, space1) {
            float values[4];
            vec3 colors[2];
        };
        vertex {
            vec4 main(vec3 position @ POSITION) @ gl_Position {
                float scale = values[0] + values[1];
                vec3 color = colors[0];
                return vec4(position * scale + color, 1.0);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "struct UniformArrayElementF32 {\n"
        "    @size(16) value: f32,\n"
        "};"
    ) in generated
    assert (
        "struct TestBuffer {\n"
        "    @align(16) values: array<UniformArrayElementF32, 4>,\n"
        "    colors: array<vec3<f32>, 2>,\n"
        "};"
    ) in generated
    assert "@group(1) @binding(2)\nvar<uniform> _TestBuffer: TestBuffer;" in generated
    assert (
        "var scale: f32 = (_TestBuffer.values[0].value + "
        "_TestBuffer.values[1].value);" in generated
    )
    assert "var color: vec3<f32> = _TestBuffer.colors[0];" in generated
    validate_wgsl_with_naga(tmp_path, generated)


def test_wgsl_codegen_lowers_uniform_blocks_to_uniform_struct_bindings():
    shader = """
    shader WGSLUniformBlock {
        uniform Camera @set(2) @binding(3) {
            mat4 viewProj;
            vec4 tint;
        };
        vertex {
            vec4 main(vec3 position @ POSITION) @ gl_Position {
                vec4 projected = viewProj * vec4(position, 1.0);
                return projected + tint;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "struct Camera {\n" "    viewProj: mat4x4<f32>,\n" "    tint: vec4<f32>,\n" "};"
    ) in generated
    assert "@group(2) @binding(3)\nvar<uniform> _Camera: Camera;" in generated
    assert (
        "var projected: vec4<f32> = " "(_Camera.viewProj * vec4<f32>(position, 1.0));"
    ) in generated
    assert "return (projected + _Camera.tint);" in generated


def test_wgsl_codegen_rejects_resource_members_in_uniform_buffers():
    shader = """
    shader WGSLUniformResourceMember {
        cbuffer Bad {
            sampler2D colorTex;
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target does not support resource member Bad\.colorTex "
            r"of type sampler2D inside uniform buffers"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))

    array_shader = """
    shader WGSLUniformResourceMemberArray {
        cbuffer Bad {
            sampler2D colorTex[2];
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target does not support resource member Bad\.colorTex "
            r"of type sampler2D inside uniform buffers"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(array_shader))


def test_wgsl_codegen_rejects_storage_buffer_members_in_uniform_buffers():
    shader = """
    shader WGSLUniformStorageBufferMember {
        cbuffer Bad {
            StructuredBuffer<float> values;
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target does not support storage-buffer resource member "
            r"Bad\.values inside uniform buffers"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_unsized_array_members_in_uniform_buffers():
    shader = """
    shader WGSLUniformRuntimeArray {
        cbuffer Bad {
            float values[];
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target does not support runtime-sized array member "
            r"Bad\.values inside uniform buffers"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_lowers_glsl_buffer_blocks_to_storage_struct_bindings():
    shader = """
    shader WGSLBufferBlocks {
        layout(std430, set = 1, binding = 2) readonly buffer InputBlock {
            float values[];
        } inputBlock;
        layout(std430, binding = 3) buffer OutputBlock {
            float values[];
        } outputBlock;
        compute {
            void main(uint3 gid @ gl_GlobalInvocationID) {
                outputBlock.values[gid.x] = inputBlock.values[gid.x];
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert ("struct InputBlock {\n" "    values: array<f32>,\n" "};") in generated
    assert ("struct OutputBlock {\n" "    values: array<f32>,\n" "};") in generated
    assert (
        "@group(1) @binding(2)\nvar<storage, read> inputBlock: InputBlock;" in generated
    )
    assert (
        "@group(0) @binding(3)\nvar<storage, read_write> outputBlock: OutputBlock;"
        in generated
    )
    assert "outputBlock.values[gid.x] = inputBlock.values[gid.x];" in generated


def test_wgsl_codegen_lowers_layoutless_buffer_blocks_as_std430_storage():
    shader = """
    shader WGSLImplicitBufferBlock {
        struct ParticleBuffer {
            float positions[];
        }
        buffer ParticleBuffer particleBuffer;
        compute {
            void main(uint3 gid @ gl_GlobalInvocationID) {
                particleBuffer.positions[gid.x] = 1.0;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "struct ParticleBuffer {\n" "    positions: array<f32>,\n" "};"
    ) in generated
    assert (
        "@group(0) @binding(0)\n"
        "var<storage, read_write> particleBuffer: ParticleBuffer;"
    ) in generated
    assert "particleBuffer.positions[gid.x] = 1.0;" in generated


def test_wgsl_codegen_rejects_glsl_buffer_block_parameters():
    shader = """
    shader WGSLBufferBlockParameters {
        struct InputBlock {
            float values[];
        };
        float readFirst(InputBlock block @glsl_buffer_block(std430) @readonly) {
            return block.values[0];
        }
        InputBlock inputBlock @glsl_buffer_block(std430) @binding(0) @readonly;
        InputBlock outputBlock @glsl_buffer_block(std430) @binding(1);
        compute {
            void main() {
                outputBlock.values[0] = readFirst(inputBlock);
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="does not support GLSL buffer block parameters yet",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


@pytest.mark.parametrize(
    ("declaration", "expected"),
    [
        (
            """
            layout(std140, binding = 0) buffer BadBlock {
                vec4 value;
            } badBlock;
            """,
            "only supports std430 GLSL buffer block layout",
        ),
        (
            """
            struct BadBlock {
                float values[];
            };
            BadBlock badBlocks[2] @glsl_buffer_block(std430) @binding(0);
            """,
            "does not support GLSL buffer block arrays yet",
        ),
        (
            """
            layout(std430, binding = 0) buffer BadBlock {
                sampler2D colorTex;
            } badBlock;
            """,
            r"does not support resource member BadBlock\.colorTex",
        ),
    ],
)
def test_wgsl_codegen_rejects_unsupported_glsl_buffer_block_shapes(
    declaration, expected
):
    shader = f"""
    shader WGSLUnsupportedBufferBlocks {{
        {declaration}
        compute {{
            void main() {{
                return;
            }}
        }}
    }}
    """

    with pytest.raises(ValueError, match=expected):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_writes_to_readonly_glsl_buffer_blocks():
    shader = """
    shader WGSLReadonlyBufferBlockWrite {
        layout(std430, binding = 0) readonly buffer ReadBlock {
            float values[];
        } readBlock;
        compute {
            void main() {
                readBlock.values[0] = 1.0;
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=r"cannot write read-only GLSL buffer block resource readBlock",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_lowers_structured_buffers_to_storage_bindings():
    shader = """
    shader WGSLStructuredBuffers {
        StructuredBuffer<float> values @set(2) @binding(4);
        RWStructuredBuffer<float> outValues;
        compute {
            void main(uint3 gid @ gl_GlobalInvocationID) {
                outValues[gid.x] = values[gid.x];
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(2) @binding(4)\nvar<storage, read> values: array<f32>;" in generated
    assert (
        "@group(0) @binding(5)\n"
        "var<storage, read_write> outValues: array<f32>;" in generated
    )
    assert "outValues[gid.x] = values[gid.x];" in generated


def test_wgsl_codegen_lowers_structured_buffer_access_helpers():
    shader = """
    shader WGSLStructuredBufferHelpers {
        struct Payload {
            vec4 color;
            float weight;
        };
        StructuredBuffer<Payload> values;
        RWStructuredBuffer<Payload> outValues;
        compute {
            void main(uint3 gid @ gl_GlobalInvocationID) {
                Payload first = buffer_load(values, gid.x);
                Payload second = values.Load(gid.y);
                buffer_store(outValues, gid.x, first);
                outValues.Store(gid.y, second);
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var<storage, read> values: array<Payload>;" in generated
    assert "var<storage, read_write> outValues: array<Payload>;" in generated
    assert "var first: Payload = values[gid.x];" in generated
    assert "var second: Payload = values[gid.y];" in generated
    assert "outValues[gid.x] = first;" in generated
    assert "outValues[gid.y] = second;" in generated
    assert "buffer_load" not in generated
    assert "buffer_store" not in generated
    assert ".Load" not in generated
    assert ".Store" not in generated


def test_wgsl_codegen_lowers_stage_resource_parameters_to_module_bindings():
    shader = """
    shader WGSLStageResourceParameters {
        struct MatMulParams {
            uint row_dim_x;
            uint col_dim_x;
            uint inner_dim;
        };
        compute {
            void main(
                constant MatMulParams& params @buffer(0),
                StructuredBuffer<float> A @buffer(1),
                StructuredBuffer<float> B @buffer(2),
                RWStructuredBuffer<float> X @buffer(3),
                uint3 gid @ gl_GlobalInvocationID
            ) {
                uint index = gid.x;
                buffer_store(
                    X,
                    index,
                    buffer_load(A, index) + buffer_load(B, index) + float(params.inner_dim)
                );
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar<uniform> params: MatMulParams;" in generated
    assert "@group(0) @binding(1)\nvar<storage, read> A: array<f32>;" in generated
    assert "@group(0) @binding(2)\nvar<storage, read> B: array<f32>;" in generated
    assert "@group(0) @binding(3)\nvar<storage, read_write> X: array<f32>;" in generated
    assert "fn compute_main(@builtin(global_invocation_id) gid: vec3<u32>)" in generated
    assert "StructuredBuffer<float> A" not in generated
    assert "RWStructuredBuffer<float> X" not in generated
    assert "constant MatMulParams" not in generated
    assert "var index: u32 = gid.x;" in generated
    assert "X[index] = ((A[index] + B[index]) + f32(params.inner_dim));" in generated


def test_wgsl_codegen_lowers_constant_buffer_stage_parameters_to_uniform_bindings():
    shader = """
    shader WGSLConstantBufferStageParameter {
        struct Params {
            uint count;
        };
        compute {
            void main(
                ConstantBuffer<Params> params @buffer(2),
                RWStructuredBuffer<float> values @buffer(3),
                uint3 gid @ gl_GlobalInvocationID
            ) {
                if (gid.x < params.count) {
                    buffer_store(values, gid.x, 1.0);
                }
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(2)\nvar<uniform> params: Params;" in generated
    assert (
        "@group(0) @binding(3)\nvar<storage, read_write> values: array<f32>;"
        in generated
    )
    assert "ConstantBuffer<Params> params" not in generated
    assert "params.count" in generated


def test_wgsl_codegen_pads_uniform_struct_scalar_arrays(tmp_path):
    shader = """
    shader WGSLConstantBufferScalarArray {
        struct Params {
            float weights[4];
        };
        compute {
            void main(
                ConstantBuffer<Params> params @buffer(2),
                uint3 gid @ gl_GlobalInvocationID
            ) {
                float weight = params.weights[0];
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert generated.index("struct UniformArrayElementF32") < generated.index(
        "struct Params"
    )
    assert (
        "struct Params {\n"
        "    @align(16) weights: array<UniformArrayElementF32, 4>,\n"
        "};"
    ) in generated
    assert "var weight: f32 = params.weights[0].value;" in generated
    validate_wgsl_with_naga(tmp_path, generated)


def test_wgsl_codegen_rejects_readonly_structured_buffer_stores():
    shader = """
    shader WGSLReadonlyStructuredBufferStore {
        StructuredBuffer<float> values;
        compute {
            void main() {
                buffer_store(values, 0, 1.0);
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="cannot store through read-only StructuredBuffer",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


@pytest.mark.parametrize(
    ("declaration", "expected"),
    [
        (
            "AppendStructuredBuffer<float> appendValues;",
            "does not support AppendStructuredBuffer resources yet",
        ),
        (
            "ConsumeStructuredBuffer<float> consumeValues;",
            "does not support ConsumeStructuredBuffer resources yet",
        ),
        (
            "ByteAddressBuffer rawBytes;",
            "does not support ByteAddressBuffer resources yet",
        ),
        (
            "RWByteAddressBuffer rawBytes;",
            "does not support RWByteAddressBuffer resources yet",
        ),
    ],
)
def test_wgsl_codegen_rejects_unsupported_storage_buffer_resource_forms(
    declaration, expected
):
    shader = f"""
    shader WGSLUnsupportedStorageBufferForms {{
        {declaration}
        compute {{
            void main() {{
                return;
            }}
        }}
    }}
    """

    with pytest.raises(ValueError, match=expected):
        WGSLCodeGen().generate(parse_shader(shader))


@pytest.mark.parametrize(
    ("statement", "expected"),
    [
        (
            "buffer_dimensions(values);",
            "does not support storage buffer helper buffer_dimensions yet",
        ),
        (
            "values.GetDimensions();",
            "does not support storage buffer member helper GetDimensions yet",
        ),
    ],
)
def test_wgsl_codegen_rejects_unsupported_structured_buffer_helpers(
    statement, expected
):
    shader = f"""
    shader WGSLUnsupportedStructuredBufferHelpers {{
        StructuredBuffer<float> values;
        compute {{
            void main() {{
                {statement}
                return;
            }}
        }}
    }}
    """

    with pytest.raises(ValueError, match=expected):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_lowers_buffer_pointers_to_storage_bindings():
    shader = """
    shader WGSLBufferPointers {
        float readAt(buffer float* values, int index) {
            return values[index];
        }
        float readAlias(buffer float* values, int index) {
            return readAt(values, index);
        }
        void writeAt(buffer float* values, int index, float value) {
            values[index] = value;
        }
        compute {
            buffer float* inputValues;
            buffer float* outputValues;
            void main(uint3 gid @ gl_GlobalInvocationID) {
                float value = readAlias(inputValues, int(gid.x));
                writeAt(outputValues, int(gid.x), value);
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "@group(0) @binding(0)\nvar<storage, read_write> inputValues: array<f32>;"
        in generated
    )
    assert (
        "@group(0) @binding(1)\nvar<storage, read_write> outputValues: array<f32>;"
        in generated
    )
    assert (
        "fn readAt(values: ptr<storage, array<f32>, read_write>, index: i32) -> f32"
        in generated
    )
    assert "return (*values)[index];" in generated
    assert "return readAt(values, index);" in generated
    assert "(*values)[index] = value;" in generated
    assert "var value: f32 = readAlias(&inputValues, i32(gid.x));" in generated
    assert "writeAt(&outputValues, i32(gid.x), value);" in generated


def test_wgsl_codegen_emits_unique_entry_names_for_duplicate_stages():
    shader = """
    shader WGSLDuplicateComputeStages {
        compute {
            void main() {
                return;
            }
        }
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "fn compute_main()" in generated
    assert "fn compute_main_1()" in generated


def test_wgsl_codegen_rejects_structured_buffers_inside_user_structs():
    shader = """
    shader WGSLStructuredBufferMember {
        struct Payload {
            StructuredBuffer<float> values;
            float factor;
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="WGSL target only supports StructuredBuffer resources as module-scope storage bindings",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_structured_buffer_parameters():
    shader = """
    shader WGSLStructuredBufferParameter {
        float readFirst(StructuredBuffer<float> values) {
            return values[0];
        }
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="WGSL target does not support StructuredBuffer parameters yet",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_does_not_rewrite_shadowed_cbuffer_member_identifiers():
    shader = """
    shader WGSLCBufferShadowing {
        cbuffer TestBuffer {
            float values[4];
        };
        fragment {
            vec4 main() @ gl_FragColor {
                float values = 1.0;
                return vec4(values);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var values: f32 = 1.0;" in generated
    assert "return vec4<f32>(values);" in generated
    assert "_TestBuffer.values" not in generated


def test_wgsl_codegen_allows_resource_like_user_type_names():
    shader = """
    shader WGSLResourceLikeNames {
        struct TextureInfo {
            vec4 color;
        };
        TextureInfo makeInfo() {
            TextureInfo info;
            info.color = vec4(1.0);
            return info;
        }
        fragment {
            vec4 main() @ gl_FragColor {
                TextureInfo info = makeInfo();
                return info.color;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "struct TextureInfo" in generated
    assert "fn makeInfo() -> TextureInfo" in generated
    assert "var info: TextureInfo;" in generated


def test_wgsl_codegen_escapes_reserved_struct_fields_and_member_accesses():
    shader = """
    shader WGSLReservedStructFields {
        struct Light {
            int type;
            float match;
        };

        float readLight(Light light) {
            return float(light.type) + light.match;
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "struct Light {\n    type_: i32,\n    match_: f32,\n};" in generated
    assert "return (f32(light.type_) + light.match_);" in generated
    assert " type:" not in generated
    assert " match:" not in generated
    assert "light.type;" not in generated
    assert "light.match;" not in generated


def test_wgsl_codegen_escapes_reserved_resources_functions_and_locals():
    shader = """
    shader WGSLReservedFunctionIdentifiers {
        sampler2D type;

        float match(float type, float match) {
            float while = type + match;
            return while;
        }

        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                float value = match(uv.x, uv.y);
                return texture(type, uv) + vec4(value);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar type_: texture_2d<f32>;" in generated
    assert "@group(0) @binding(1)\nvar type__sampler: sampler;" in generated
    assert "fn match_(type_: f32, match_: f32) -> f32" in generated
    assert "var while_: f32 = (type_ + match_);" in generated
    assert "return while_;" in generated
    assert "var value: f32 = match_(uv.x, uv.y);" in generated
    assert "textureSample(type_, type__sampler, uv)" in generated
    assert "fn match(" not in generated
    assert "var while:" not in generated
    assert "textureSample(type," not in generated


def test_wgsl_aliases_format_as_noop_wgsl():
    source = "@vertex fn main() {}"

    assert format_shader_code(source, "wgsl") == source
    assert format_shader_code(source, "webgpu") == source
    assert format_shader_code(source, "shader.wgsl") == source


def test_translate_crossgl_to_wgsl(tmp_path):
    source_path = tmp_path / "shader.cgl"
    source_path.write_text(WGSL_SHADER, encoding="utf-8")

    generated = crosstl.translate(str(source_path), backend="webgpu")

    assert "@vertex" in generated
    assert "@fragment" in generated
    assert "fn fragment_main" in generated


def test_translate_metal_half_vector_aliases_to_wgsl_widens_to_f32(tmp_path):
    source_path = tmp_path / "half_aliases.metal"
    source_path.write_text(
        """
        #include <metal_stdlib>
        using namespace metal;

        half3 buildViewDir(half2 pair, half z) {
            half3 dir = half3(pair, z);
            return half3(dir.x, dir.yz);
        }

        kernel void half_alias_kernel(uint3 gid [[thread_position_in_grid]]) {
            half2 pair = half2(1.0h, 2.0h);
            half3 viewDir = buildViewDir(pair, 3.0h);
            half x = viewDir.x;
        }
        """,
        encoding="utf-8",
    )

    generated = crosstl.translate(str(source_path), backend="webgpu")

    assert "fn buildViewDir(pair: vec2<f32>, z: f32) -> vec3<f32>" in generated
    assert "var dir: vec3<f32> = vec3<f32>(pair, z);" in generated
    assert "return vec3<f32>(dir.x, dir.yz);" in generated
    assert (
        "fn compute_main(@builtin(global_invocation_id) gid: vec3<u32>)" in generated
    )
    assert "var pair: vec2<f32> = vec2<f32>(1.0, 2.0);" in generated
    assert "var viewDir: vec3<f32> = buildViewDir(pair, 3.0);" in generated
    assert "var x: f32 = viewDir.x;" in generated
    assert "f16vec" not in generated
    assert "float16" not in generated


@pytest.mark.parametrize(
    "stage",
    (
        "geometry",
        "tessellation_control",
        "tessellation_evaluation",
        "mesh",
        "task",
        "ray_generation",
    ),
)
def test_wgsl_codegen_rejects_non_webgpu_stage_targets(stage):
    ast = SimpleNamespace(functions=[], stages={})

    with pytest.raises(
        ValueError,
        match=rf"WGSL target does not support shader stage\(s\): {stage}",
    ):
        WGSLCodeGen().generate_program(ast, target_stage=stage)


def test_wgsl_codegen_rejects_do_while_statement():
    shader = """
    shader WGSLUnsupported {
        fragment {
            vec4 main() @ gl_FragColor {
                do {
                    return vec4(1.0);
                } while (false);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="WGSL target does not support do-while statements",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


@pytest.mark.parametrize(
    ("shader", "message"),
    (
        (
            """
            shader WGSLImageResource {
                image2D colorImage;
                fragment {
                    vec4 main() @ gl_FragColor {
                        return vec4(1.0);
                    }
                }
            }
            """,
            "WGSL target requires storage image resource colorImage to declare "
            "a representable image format",
        ),
        (
            """
            shader WGSLUnsupportedTextureCall {
                sampler2D colorTex;
                fragment {
                    vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                        return textureGather(colorTex, uv);
                    }
                }
            }
            """,
            "WGSL target does not support CrossGL texture function textureGather yet",
        ),
    ),
)
def test_wgsl_codegen_rejects_unsupported_resource_texture_constructs(shader, message):
    with pytest.raises(
        ValueError,
        match=message,
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_lowers_struct_texture_members_to_module_bindings():
    shader = """
    shader WGSLStructTextureResource {
        struct Material {
            vec3 tint;
            sampler2D colorTex;
        };
        uniform Material material;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(material.colorTex, uv) * vec4(material.tint, 1.0);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    struct_block = generated.split("};", 1)[0] + "};"
    assert (
        "struct Material {\n    tint: vec3<f32>,\n};" == struct_block.split("\n\n")[-1]
    )
    assert "    colorTex:" not in struct_block
    assert "@group(0) @binding(1)\nvar material_colorTex: texture_2d<f32>;" in generated
    assert "@group(0) @binding(2)\nvar material_colorTex_sampler: sampler;" in generated
    assert (
        "textureSample(material_colorTex, material_colorTex_sampler, uv)" in generated
    )
    assert "material.tint" in generated


def test_wgsl_codegen_lowers_struct_texture_members_in_helper_parameters():
    shader = """
    shader WGSLStructCubeTextureResource {
        struct EnvironmentData {
            samplerCube irradiance_map;
            float exposure;
        };
        vec4 sampleEnv(EnvironmentData env, vec3 direction) {
            return texture(env.irradiance_map, direction) * env.exposure;
        }
        uniform EnvironmentData environment;
        fragment {
            vec4 main(vec3 normal @ NORMAL) @ gl_FragColor {
                return sampleEnv(environment, normal);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    struct_block = generated.split("};", 1)[0] + "};"
    assert (
        "struct EnvironmentData {\n    exposure: f32,\n};"
        == struct_block.split("\n\n")[-1]
    )
    assert "    irradiance_map:" not in struct_block
    assert (
        "@group(0) @binding(1)\nvar environment_irradiance_map: " "texture_cube<f32>;"
    ) in generated
    assert (
        "@group(0) @binding(2)\nvar environment_irradiance_map_sampler: sampler;"
        in generated
    )
    assert (
        "fn sampleEnv(env: EnvironmentData, env_irradiance_map: texture_cube<f32>, "
        "env_irradiance_map_sampler: sampler, direction: vec3<f32>)"
    ) in generated
    assert (
        "textureSample(env_irradiance_map, env_irradiance_map_sampler, direction)"
    ) in generated
    assert (
        "return sampleEnv(environment, environment_irradiance_map, "
        "environment_irradiance_map_sampler, normal);"
    ) in generated
    assert "env.exposure" in generated


def test_wgsl_codegen_keeps_scalar_member_with_same_name_as_resource_member():
    shader = """
    shader WGSLStructResourceCollision {
        struct Textured {
            sampler2D colorTex;
        };
        struct Plain {
            float colorTex;
        };
        uniform Textured textured;
        uniform Plain plain;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(textured.colorTex, uv) + vec4(plain.colorTex);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var textured_colorTex: texture_2d<f32>;" in generated
    assert (
        "textureSample(textured_colorTex, textured_colorTex_sampler, uv)" in generated
    )
    assert "plain.colorTex" in generated
    assert "textureSample(plain_colorTex" not in generated


def test_wgsl_codegen_aliases_nested_resource_member_paths_from_initializer():
    shader = """
    shader WGSLStructResourceAlias {
        struct Material {
            vec3 albedo;
            sampler2D albedoMap;
        };
        struct Scene {
            Material materials[4];
        };
        struct GlobalUniforms {
            Scene scene;
        };
        uniform GlobalUniforms globals;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0, int materialIndex @ TEXCOORD1) @ gl_FragColor {
                Material material = globals.scene.materials[materialIndex];
                return texture(material.albedoMap, uv) * vec4(material.albedo, 1.0);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "albedoMap:" not in generated.split("struct Scene", 1)[0]
    assert "var globals_scene_materials_albedoMap: texture_2d<f32>;" in generated
    assert (
        "textureSample(globals_scene_materials_albedoMap, "
        "globals_scene_materials_albedoMap_sampler, uv)"
    ) in generated
    assert "material.albedo" in generated
    assert "material.albedoMap" not in generated


def test_wgsl_codegen_lowers_sampled_texture_resources_and_calls():
    shader = """
    shader WGSLTextureResource {
        sampler2D colorTex;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(colorTex, uv);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar colorTex: texture_2d<f32>;" in generated
    assert "@group(0) @binding(1)\nvar colorTex_sampler: sampler;" in generated
    assert "return textureSample(colorTex, colorTex_sampler, uv);" in generated


def test_wgsl_codegen_lowers_explicit_sampler_texture_calls():
    shader = """
    shader WGSLExplicitSamplerTexture {
        sampler2D colorTex;
        sampler linearSampler;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(colorTex, linearSampler, uv);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(2)\nvar linearSampler: sampler;" in generated
    assert "return textureSample(colorTex, linearSampler, uv);" in generated


@pytest.mark.parametrize(
    ("declaration", "resource_type"),
    (
        ("sampler2D textures[4];", "sampler2D"),
        ("sampler samplers[2];", "sampler"),
        ("image2D images[2];", "image2D"),
        ("StructuredBuffer<float> values[4];", "StructuredBuffer"),
        ("RWStructuredBuffer<float> values[];", "RWStructuredBuffer"),
    ),
)
def test_wgsl_codegen_rejects_resource_array_declarations(declaration, resource_type):
    shader = f"""
    shader WGSLResourceArray {{
        {declaration}
        compute {{
            void main() {{
                return;
            }}
        }}
    }}
    """

    with pytest.raises(
        ValueError,
        match=(
            rf"WGSL target does not support resource arrays of {resource_type}; "
            r"WebGPU/WGSL requires texture, sampler, image, and storage-buffer "
            r"resources to be declared as individual module-scope bindings"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_resource_array_parameters():
    shader = """
    shader WGSLResourceArrayParameter {
        vec4 sampleAt(sampler2D textures[4], int index, vec2 uv) {
            return texture(textures[index], uv);
        }
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0, int index @ TEXCOORD1) @ gl_FragColor {
                return vec4(1.0);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target does not support resource arrays of sampler2D; "
            r"WebGPU/WGSL requires texture, sampler, image, and storage-buffer "
            r"resources to be declared as individual module-scope bindings"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_emits_stage_local_resource_declarations():
    shader = """
    shader WGSLStageLocalResources {
        fragment {
            uniform sampler2D colorTex;
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(colorTex, uv);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar colorTex: texture_2d<f32>;" in generated
    assert "@group(0) @binding(1)\nvar colorTex_sampler: sampler;" in generated
    assert "return textureSample(colorTex, colorTex_sampler, uv);" in generated


def test_wgsl_codegen_lowers_texture_helper_parameters_and_lod_size_calls():
    shader = """
    shader WGSLTextureHelpers {
        samplerCube envMap;
        vec4 sampleEnv(samplerCube tex, vec3 direction) {
            uint2 size = textureSize(tex, 0);
            return textureLod(tex, direction, 1.0);
        }
        fragment {
            vec4 main(vec3 normal @ NORMAL) @ gl_FragColor {
                return sampleEnv(envMap, normal);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var envMap: texture_cube<f32>;" in generated
    assert "var envMap_sampler: sampler;" in generated
    assert (
        "fn sampleEnv(tex: texture_cube<f32>, tex_sampler: sampler, "
        "direction: vec3<f32>) -> vec4<f32>"
    ) in generated
    assert "var size: vec2<u32> = textureDimensions(tex, 0);" in generated
    assert "textureSampleLevel(tex, tex_sampler, direction, 1.0)" in generated
    assert "return sampleEnv(envMap, envMap_sampler, normal);" in generated


def test_wgsl_codegen_lowers_split_sampler_lod_grad_and_offset_calls():
    shader = """
    shader WGSLTextureSamplingForms {
        sampler2D colorTex;
        sampler linearSampler;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                vec2 ddx = vec2(0.1, 0.0);
                vec2 ddy = vec2(0.0, 0.1);
                ivec2 offset = ivec2(1, 0);
                return textureLodOffset(colorTex, linearSampler, uv, 1.0, offset)
                    + textureGrad(colorTex, linearSampler, uv, ddx, ddy)
                    + textureGradOffset(colorTex, linearSampler, uv, ddx, ddy, offset)
                    + textureOffset(colorTex, linearSampler, uv, offset)
                    + textureOffset(colorTex, linearSampler, uv, offset, 0.25)
                    + textureOffset(colorTex, uv, offset, 0.5);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "textureSampleLevel(colorTex, linearSampler, uv, 1.0, offset)" in generated
    assert "textureSampleGrad(colorTex, linearSampler, uv, ddx, ddy)" in generated
    assert (
        "textureSampleGrad(colorTex, linearSampler, uv, ddx, ddy, offset)" in generated
    )
    assert "textureSample(colorTex, linearSampler, uv, offset)" in generated
    assert "textureSampleBias(colorTex, linearSampler, uv, 0.25, offset)" in generated
    assert "textureSampleBias(colorTex, colorTex_sampler, uv, 0.5, offset)" in generated


def test_wgsl_codegen_lowers_shadow_textures_and_comparison_samplers():
    shader = """
    shader WGSLShadowTexture {
        sampler2DShadow shadowMap;
        samplerComparisonState compareSampler;
        float sampleShadow(sampler2DShadow tex, vec2 uv, float depth) {
            return textureCompare(tex, uv, depth);
        }
        fragment {
            float main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return textureCompare(shadowMap, compareSampler, uv, 0.5)
                    + textureCompareOffset(shadowMap, compareSampler, uv, 0.25, ivec2(1, 0))
                    + textureCompareLod(shadowMap, compareSampler, uv, 0.75, 0)
                    + textureCompareLodOffset(shadowMap, compareSampler, uv, 0.875, 0, ivec2(0, 1))
                    + sampleShadow(shadowMap, uv, 0.625);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar shadowMap: texture_depth_2d;" in generated
    assert (
        "@group(0) @binding(1)\nvar shadowMap_sampler: sampler_comparison;" in generated
    )
    assert "@group(0) @binding(2)\nvar compareSampler: sampler_comparison;" in generated
    assert (
        "fn sampleShadow(tex: texture_depth_2d, tex_sampler: sampler_comparison, "
        "uv: vec2<f32>, depth: f32) -> f32"
    ) in generated
    assert "return textureSampleCompare(tex, tex_sampler, uv, depth);" in generated
    assert "textureSampleCompare(shadowMap, compareSampler, uv, 0.5)" in generated
    assert (
        "textureSampleCompare(shadowMap, compareSampler, uv, 0.25, " "vec2<i32>(1, 0))"
    ) in generated
    assert "textureSampleCompareLevel(shadowMap, compareSampler, uv, 0.75)" in generated
    assert (
        "textureSampleCompareLevel(shadowMap, compareSampler, uv, 0.875, "
        "vec2<i32>(0, 1))"
    ) in generated
    assert "sampleShadow(shadowMap, shadowMap_sampler, uv, 0.625)" in generated


def test_wgsl_codegen_rejects_plain_sampler_for_explicit_shadow_compare():
    shader = """
    shader WGSLBadShadowSampler {
        sampler2DShadow shadowMap;
        sampler plainSampler;
        fragment {
            float main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return textureCompare(shadowMap, plainSampler, uv, 0.5);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target requires textureCompare\(\) explicit sampler operand "
            r"to use samplerComparisonState"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_nonzero_shadow_compare_lod():
    shader = """
    shader WGSLBadShadowLod {
        sampler2DShadow shadowMap;
        samplerComparisonState compareSampler;
        fragment {
            float main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return textureCompareLod(shadowMap, compareSampler, uv, 0.5, 1);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            r"WGSL target only lowers textureCompareLod\(\) when the explicit "
            r"LOD operand is literal 0"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_lowers_mod_builtin_to_floor_semantics_expression():
    shader = """
    shader WGSLModBuiltin {
        compute {
            void main() {
                vec2 uv = vec2(-1.25, 2.75);
                vec2 tile = mod((uv * 4.0) - vec2(2.0), 1.0);
                vec2 wrapped = mod(tile, vec2(0.25, 0.5));
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "var tile: vec2<f32> = ((((uv * 4.0) - vec2<f32>(2.0))) - "
        "((1.0) * floor((((uv * 4.0) - vec2<f32>(2.0))) / (1.0))));"
    ) in generated
    assert (
        "var wrapped: vec2<f32> = ((tile) - "
        "((vec2<f32>(0.25, 0.5)) * floor((tile) / (vec2<f32>(0.25, 0.5)))));"
    ) in generated
    assert "mod(" not in generated


def test_wgsl_codegen_lowers_compute_barrier_to_workgroup_barrier():
    shader = """
    shader WGSLBarrier {
        compute {
            layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in;
            void main() {
                barrier();
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "workgroupBarrier();" in generated
    assert "barrier();" not in generated


def test_wgsl_codegen_lowers_prefix_increment_and_decrement_statements():
    shader = """
    shader WGSLPrefixUpdate {
        compute {
            void main() {
                int i = 0;
                ++i;
                --i;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "++i;" not in generated
    assert "--i;" not in generated
    assert "i += 1;" in generated
    assert "i -= 1;" in generated


def test_wgsl_codegen_lowers_switch_default_case():
    shader = """
    shader WGSLSwitchDefault {
        compute {
            void main() {
                uint mode = 1u;
                switch (mode) {
                    case 0u:
                        mode = 2u;
                        break;
                    default:
                        mode = 3u;
                        break;
                }
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "case 0:" in generated
    assert "default: {" in generated
    assert "case : {" not in generated


def test_wgsl_codegen_rejects_barrier_outside_compute_stages():
    shader = """
    shader WGSLFragmentBarrier {
        fragment {
            vec4 main() @ gl_FragColor {
                barrier();
                return vec4(1.0);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=r"WGSL target only supports barrier\(\) inside compute stages",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_direct_builtin_references_in_helpers():
    shader = """
    shader WGSLHelperBuiltin {
        uint helper() {
            return gl_GlobalInvocationID.x;
        }
        compute {
            void main() {
                uint lane = helper();
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support direct builtin identifier\\(s\\) "
            "in helper function helper: gl_GlobalInvocationID"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_compute_builtin_references_in_fragment_stage():
    shader = """
    shader WGSLFragmentComputeBuiltin {
        fragment {
            vec4 main() @ gl_FragColor {
                uint lane = gl_GlobalInvocationID.x;
                return vec4(1.0);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support implicit builtin identifier\\(s\\) "
            "in fragment stage: gl_GlobalInvocationID"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_implicit_builtin_parameter_name_collision():
    shader = """
    shader WGSLBuiltinNameCollision {
        compute {
            void main(uint3 global_invocation_id) {
                uint lane = gl_GlobalInvocationID.x;
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target cannot inject builtin global_invocation_id because "
            "an entry parameter already uses that name without "
            "@builtin\\(global_invocation_id\\)"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_barriers_in_helpers_with_specific_diagnostic():
    shader = """
    shader WGSLHelperBarrier {
        void sync() {
            barrier();
            return;
        }
        compute {
            void main() {
                sync();
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support barrier\\(\\) inside helper function "
            "sync yet"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))
