from types import SimpleNamespace

import pytest

import crosstl
import crosstl.translator.codegen as codegen
from crosstl.formatter import format_shader_code
from crosstl.translator.codegen.wgsl_codegen import WGSLCodeGen
from crosstl.translator.lexer import Lexer
from crosstl.translator.parser import Parser

WGSL_SHADER = """
shader WGSLSmoke {
    struct VSInput {
        vec3 position @ POSITION;
        vec2 uv @ TEXCOORD0;
    };
    struct VSOutput {
        vec4 position @ gl_Position;
        vec2 uv @ TEXCOORD0;
    };
    vertex {
        VSOutput main(VSInput input) {
            VSOutput output;
            output.position = vec4(input.position, 1.0);
            output.uv = input.uv;
            return output;
        }
    }
    fragment {
        vec4 main(VSOutput input) @ gl_FragColor {
            return vec4(input.uv, 0.0, 1.0);
        }
    }
}
"""

WGSL_COMPUTE_SHADER = """
shader WGSLCompute {
    compute {
        layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
        void main() {
            return;
        }
    }
}
"""


def parse_shader(source):
    return Parser(Lexer(source).get_tokens()).parse()


def test_wgsl_backend_is_target_only():
    spec = codegen.get_backend("webgpu")

    assert spec is not None
    assert spec.name == "wgsl"
    assert spec.source_registry_name is None
    assert "wgsl" not in codegen.source_backend_names()
    assert codegen.normalize_backend_name("shader.wgsl") == "wgsl"
    assert codegen.get_backend_extension("webgpu") == ".wgsl"
    assert isinstance(codegen.get_codegen("wgsl"), WGSLCodeGen)


def test_wgsl_codegen_emits_vertex_and_fragment_entry_points():
    generated = WGSLCodeGen().generate(parse_shader(WGSL_SHADER))

    assert generated.startswith("// Generated by CrossGL for WebGPU WGSL\n")
    assert "struct VSInput" in generated
    assert "@location(0) position: vec3<f32>," in generated
    assert "@location(2) uv: vec2<f32>," in generated
    assert "@builtin(position) position: vec4<f32>," in generated
    assert "@vertex\nfn vertex_main(input: VSInput) -> VSOutput" in generated
    assert (
        "@fragment\nfn fragment_main(input: VSOutput) -> @location(0) vec4<f32>"
        in generated
    )
    assert "vec4<f32>(input.position, 1.0)" in generated
    assert "return vec4<f32>(input.uv, 0.0, 1.0);" in generated


def test_wgsl_codegen_preserves_explicit_io_attributes():
    shader = """
    shader WGSLExplicitAttributes {
        struct FragmentInput {
            vec4 position @builtin(position);
            vec2 uv @location(3) @interpolate(flat);
        };
        fragment {
            vec4 main(FragmentInput input) @location(1) {
                return input.position;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@builtin(position) position: vec4<f32>," in generated
    assert "@location(3) @interpolate(flat) uv: vec2<f32>," in generated
    assert (
        "fn fragment_main(input: FragmentInput) -> @location(1) vec4<f32>" in generated
    )


def test_wgsl_codegen_emits_compute_workgroup_size():
    generated = WGSLCodeGen().generate(parse_shader(WGSL_COMPUTE_SHADER))

    assert "@compute" in generated
    assert "@workgroup_size(8, 4, 1)" in generated
    assert "fn compute_main()" in generated


def test_wgsl_codegen_emits_compute_builtin_parameter():
    shader = """
    shader WGSLComputeBuiltin {
        compute {
            layout(local_size_x = 4) in;
            void main(uint3 gid @ gl_GlobalInvocationID) {
                barrier();
                uint lane = gid.x;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@workgroup_size(4, 1, 1)" in generated
    assert "fn compute_main(@builtin(global_invocation_id) gid: vec3<u32>)" in generated
    assert "workgroupBarrier();" in generated
    assert "var lane: u32 = gid.x;" in generated


def test_wgsl_codegen_injects_direct_compute_builtin_references():
    shader = """
    shader WGSLDirectComputeBuiltin {
        compute {
            layout(local_size_x = 4) in;
            void main() {
                uint lane = gl_GlobalInvocationID.x;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "fn compute_main(@builtin(global_invocation_id) "
        "global_invocation_id: vec3<u32>)"
    ) in generated
    assert "var lane: u32 = global_invocation_id.x;" in generated


def test_wgsl_codegen_treats_attribute_compute_functions_as_entry_points():
    shader = """
    shader WGSLAttributeComputeEntry {
        @compute
        @workgroup_size(2, 3, 4)
        void main() {
            uint lane = gl_GlobalInvocationID.x;
            uint3 block = gl_WorkGroupSize;
            return;
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@compute" in generated
    assert "@workgroup_size(2, 3, 4)" in generated
    assert (
        "fn compute_main(@builtin(global_invocation_id) "
        "global_invocation_id: vec3<u32>)"
    ) in generated
    assert "var lane: u32 = global_invocation_id.x;" in generated
    assert "var block: vec3<u32> = vec3<u32>(2u, 3u, 4u);" in generated


def test_wgsl_codegen_does_not_treat_semantic_attributes_as_stage_entries():
    shader = """
    shader WGSLSemanticAttributeFunction {
        vec4 main(vec4 pos @ Out_Position) @ Out_Color {
            return pos;
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "fn main(" in generated
    assert "@out_color" not in generated.lower()


def test_wgsl_codegen_emits_resource_address_spaces_and_bindings():
    shader = """
    shader WGSLResources {
        uniform vec4 tint;
        buffer float values[4];
        var<workgroup> scratch: float[4];
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar<uniform> tint: vec4<f32>;" in generated
    assert (
        "@group(0) @binding(1)\n" "var<storage, read_write> values: array<f32, 4>;"
    ) in generated
    assert "var<workgroup> scratch: array<f32, 4>;" in generated


def test_wgsl_codegen_allows_resource_like_user_type_names():
    shader = """
    shader WGSLResourceLikeNames {
        struct TextureInfo {
            vec4 color;
        };
        TextureInfo makeInfo() {
            TextureInfo info;
            info.color = vec4(1.0);
            return info;
        }
        fragment {
            vec4 main() @ gl_FragColor {
                TextureInfo info = makeInfo();
                return info.color;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "struct TextureInfo" in generated
    assert "fn makeInfo() -> TextureInfo" in generated
    assert "var info: TextureInfo;" in generated


def test_wgsl_aliases_format_as_noop_wgsl():
    source = "@vertex fn main() {}"

    assert format_shader_code(source, "wgsl") == source
    assert format_shader_code(source, "webgpu") == source
    assert format_shader_code(source, "shader.wgsl") == source


def test_translate_crossgl_to_wgsl(tmp_path):
    source_path = tmp_path / "shader.cgl"
    source_path.write_text(WGSL_SHADER, encoding="utf-8")

    generated = crosstl.translate(str(source_path), backend="webgpu")

    assert "@vertex" in generated
    assert "@fragment" in generated
    assert "fn fragment_main" in generated


@pytest.mark.parametrize(
    "stage",
    (
        "geometry",
        "tessellation_control",
        "tessellation_evaluation",
        "mesh",
        "task",
        "ray_generation",
    ),
)
def test_wgsl_codegen_rejects_non_webgpu_stage_targets(stage):
    ast = SimpleNamespace(functions=[], stages={})

    with pytest.raises(
        ValueError,
        match=rf"WGSL target does not support shader stage\(s\): {stage}",
    ):
        WGSLCodeGen().generate_program(ast, target_stage=stage)


def test_wgsl_codegen_rejects_do_while_statement():
    shader = """
    shader WGSLUnsupported {
        fragment {
            vec4 main() @ gl_FragColor {
                do {
                    return vec4(1.0);
                } while (false);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="WGSL target does not support do-while statements",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


@pytest.mark.parametrize(
    ("shader", "message"),
    (
        (
            """
            shader WGSLResource {
                sampler2D colorTex;
                fragment {
                    vec4 main() @ gl_FragColor {
                        return vec4(1.0);
                    }
                }
            }
            """,
            "WGSL target does not support CrossGL resource type sampler2D yet; "
            "split texture/sampler/storage bindings are required",
        ),
        (
            """
            shader WGSLTextureCall {
                fragment {
                    vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                        return texture(colorTex, linearSampler, uv);
                    }
                }
            }
            """,
            "WGSL target does not support CrossGL texture function texture yet; "
            "split texture/sampler lowering is required",
        ),
    ),
)
def test_wgsl_codegen_rejects_unsupported_resource_texture_compute_constructs(
    shader, message
):
    with pytest.raises(
        ValueError,
        match=message,
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_lowers_compute_barrier_to_workgroup_barrier():
    shader = """
    shader WGSLBarrier {
        compute {
            layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in;
            void main() {
                barrier();
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "workgroupBarrier();" in generated
    assert "barrier();" not in generated


def test_wgsl_codegen_rejects_barrier_outside_compute_stages():
    shader = """
    shader WGSLFragmentBarrier {
        fragment {
            vec4 main() @ gl_FragColor {
                barrier();
                return vec4(1.0);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=r"WGSL target only supports barrier\(\) inside compute stages",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_direct_builtin_references_in_helpers():
    shader = """
    shader WGSLHelperBuiltin {
        uint helper() {
            return gl_GlobalInvocationID.x;
        }
        compute {
            void main() {
                uint lane = helper();
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support direct builtin identifier\\(s\\) "
            "in helper function helper: gl_GlobalInvocationID"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_compute_builtin_references_in_fragment_stage():
    shader = """
    shader WGSLFragmentComputeBuiltin {
        fragment {
            vec4 main() @ gl_FragColor {
                uint lane = gl_GlobalInvocationID.x;
                return vec4(1.0);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support implicit builtin identifier\\(s\\) "
            "in fragment stage: gl_GlobalInvocationID"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_implicit_builtin_parameter_name_collision():
    shader = """
    shader WGSLBuiltinNameCollision {
        compute {
            void main(uint3 global_invocation_id) {
                uint lane = gl_GlobalInvocationID.x;
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target cannot inject builtin global_invocation_id because "
            "an entry parameter already uses that name without "
            "@builtin\\(global_invocation_id\\)"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_barriers_in_helpers_with_specific_diagnostic():
    shader = """
    shader WGSLHelperBarrier {
        void sync() {
            barrier();
            return;
        }
        compute {
            void main() {
                sync();
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support barrier\\(\\) inside helper function "
            "sync yet"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))
