from types import SimpleNamespace

import pytest

import crosstl
import crosstl.translator.codegen as codegen
from crosstl.formatter import format_shader_code
from crosstl.translator.codegen.wgsl_codegen import WGSLCodeGen
from crosstl.translator.lexer import Lexer
from crosstl.translator.parser import Parser

WGSL_SHADER = """
shader WGSLSmoke {
    struct VSInput {
        vec3 position @ POSITION;
        vec2 uv @ TEXCOORD0;
    };
    struct VSOutput {
        vec4 position @ gl_Position;
        vec2 uv @ TEXCOORD0;
    };
    vertex {
        VSOutput main(VSInput input) {
            VSOutput output;
            output.position = vec4(input.position, 1.0);
            output.uv = input.uv;
            return output;
        }
    }
    fragment {
        vec4 main(VSOutput input) @ gl_FragColor {
            return vec4(input.uv, 0.0, 1.0);
        }
    }
}
"""

WGSL_COMPUTE_SHADER = """
shader WGSLCompute {
    compute {
        layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
        void main() {
            return;
        }
    }
}
"""


def parse_shader(source):
    return Parser(Lexer(source).get_tokens()).parse()


def test_wgsl_backend_is_target_only():
    spec = codegen.get_backend("webgpu")

    assert spec is not None
    assert spec.name == "wgsl"
    assert spec.source_registry_name is None
    assert "wgsl" not in codegen.source_backend_names()
    assert codegen.normalize_backend_name("shader.wgsl") == "wgsl"
    assert codegen.get_backend_extension("webgpu") == ".wgsl"
    assert isinstance(codegen.get_codegen("wgsl"), WGSLCodeGen)


def test_wgsl_codegen_emits_vertex_and_fragment_entry_points():
    generated = WGSLCodeGen().generate(parse_shader(WGSL_SHADER))

    assert generated.startswith("// Generated by CrossGL for WebGPU WGSL\n")
    assert "struct VSInput" in generated
    assert "@location(0) position: vec3<f32>," in generated
    assert "@location(2) uv: vec2<f32>," in generated
    assert "@builtin(position) position: vec4<f32>," in generated
    assert "@vertex\nfn vertex_main(input: VSInput) -> VSOutput" in generated
    assert (
        "@fragment\nfn fragment_main(input: VSOutput) -> @location(0) vec4<f32>"
        in generated
    )
    assert "vec4<f32>(input.position, 1.0)" in generated
    assert "return vec4<f32>(input.uv, 0.0, 1.0);" in generated


def test_wgsl_codegen_preserves_explicit_io_attributes():
    shader = """
    shader WGSLExplicitAttributes {
        struct FragmentInput {
            vec4 position @builtin(position);
            vec2 uv @location(3) @interpolate(flat);
        };
        fragment {
            vec4 main(FragmentInput input) @location(1) {
                return input.position;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@builtin(position) position: vec4<f32>," in generated
    assert "@location(3) @interpolate(flat) uv: vec2<f32>," in generated
    assert (
        "fn fragment_main(input: FragmentInput) -> @location(1) vec4<f32>" in generated
    )


def test_wgsl_codegen_emits_compute_workgroup_size():
    generated = WGSLCodeGen().generate(parse_shader(WGSL_COMPUTE_SHADER))

    assert "@compute" in generated
    assert "@workgroup_size(8, 4, 1)" in generated
    assert "fn compute_main()" in generated


def test_wgsl_codegen_emits_compute_builtin_parameter():
    shader = """
    shader WGSLComputeBuiltin {
        compute {
            layout(local_size_x = 4) in;
            void main(uint3 gid @ gl_GlobalInvocationID) {
                barrier();
                uint lane = gid.x;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@workgroup_size(4, 1, 1)" in generated
    assert "fn compute_main(@builtin(global_invocation_id) gid: vec3<u32>)" in generated
    assert "workgroupBarrier();" in generated
    assert "var lane: u32 = gid.x;" in generated


def test_wgsl_codegen_injects_direct_compute_builtin_references():
    shader = """
    shader WGSLDirectComputeBuiltin {
        compute {
            layout(local_size_x = 4) in;
            void main() {
                uint lane = gl_GlobalInvocationID.x;
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "fn compute_main(@builtin(global_invocation_id) "
        "global_invocation_id: vec3<u32>)"
    ) in generated
    assert "var lane: u32 = global_invocation_id.x;" in generated


def test_wgsl_codegen_treats_attribute_compute_functions_as_entry_points():
    shader = """
    shader WGSLAttributeComputeEntry {
        @compute
        @workgroup_size(2, 3, 4)
        void main() {
            uint lane = gl_GlobalInvocationID.x;
            uint3 block = gl_WorkGroupSize;
            return;
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@compute" in generated
    assert "@workgroup_size(2, 3, 4)" in generated
    assert (
        "fn compute_main(@builtin(global_invocation_id) "
        "global_invocation_id: vec3<u32>)"
    ) in generated
    assert "var lane: u32 = global_invocation_id.x;" in generated
    assert "var block: vec3<u32> = vec3<u32>(2u, 3u, 4u);" in generated


def test_wgsl_codegen_does_not_treat_semantic_attributes_as_stage_entries():
    shader = """
    shader WGSLSemanticAttributeFunction {
        vec4 main(vec4 pos @ Out_Position) @ Out_Color {
            return pos;
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "fn main(" in generated
    assert "@out_color" not in generated.lower()


def test_wgsl_codegen_emits_resource_address_spaces_and_bindings():
    shader = """
    shader WGSLResources {
        uniform vec4 tint;
        buffer float values[4];
        var<workgroup> scratch: float[4];
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar<uniform> tint: vec4<f32>;" in generated
    assert (
        "@group(0) @binding(1)\n" "var<storage, read_write> values: array<f32, 4>;"
    ) in generated
    assert "var<workgroup> scratch: array<f32, 4>;" in generated


def test_wgsl_codegen_preserves_explicit_set_and_binding_resources():
    shader = """
    shader WGSLExplicitResourceBindings {
        layout(set = 2, binding = 4) uniform sampler2D colorTex;
        sampler explicitSampler @set(3) @binding(5);
        layout(set = 4, binding = 6) uniform vec4 tint;
        layout(set = 5, binding = 7) buffer float values[4];
        cbuffer Registered : register(b8, space6) {
            float value;
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(2) @binding(4)\nvar colorTex: texture_2d<f32>;" in generated
    assert "@group(2) @binding(5)\nvar colorTex_sampler: sampler;" in generated
    assert "@group(3) @binding(5)\nvar explicitSampler: sampler;" in generated
    assert "@group(4) @binding(6)\nvar<uniform> tint: vec4<f32>;" in generated
    assert (
        "@group(5) @binding(7)\n" "var<storage, read_write> values: array<f32, 4>;"
    ) in generated
    assert "@group(6) @binding(8)\nvar<uniform> _Registered: Registered;" in generated


def test_wgsl_auto_bindings_skip_later_explicit_bindings():
    shader = """
    shader WGSLLateExplicitBindings {
        uniform vec4 autoTint;
        sampler2D explicitTexture @binding(0);
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar explicitTexture: texture_2d<f32>;" in generated
    assert "@group(0) @binding(1)\nvar explicitTexture_sampler: sampler;" in generated
    assert "@group(0) @binding(2)\nvar<uniform> autoTint: vec4<f32>;" in generated


def test_wgsl_synthetic_sampler_skips_occupied_binding():
    shader = """
    shader WGSLSyntheticSamplerCollision {
        sampler occupied @binding(1);
        sampler2D colorTex @binding(0);
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(1)\nvar occupied: sampler;" in generated
    assert "@group(0) @binding(0)\nvar colorTex: texture_2d<f32>;" in generated
    assert "@group(0) @binding(2)\nvar colorTex_sampler: sampler;" in generated


def test_wgsl_codegen_lowers_cbuffers_to_uniform_struct_bindings():
    shader = """
    shader WGSLCBuffer {
        cbuffer TestBuffer : register(b2, space1) {
            float values[4];
            vec3 colors[2];
        };
        vertex {
            vec4 main(vec3 position @ POSITION) @ gl_Position {
                float scale = values[0] + values[1];
                vec3 color = colors[0];
                return vec4(position * scale + color, 1.0);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "struct TestBuffer {\n"
        "    values: array<f32, 4>,\n"
        "    colors: array<vec3<f32>, 2>,\n"
        "};"
    ) in generated
    assert "@group(1) @binding(2)\nvar<uniform> _TestBuffer: TestBuffer;" in generated
    assert (
        "var scale: f32 = (_TestBuffer.values[0] + _TestBuffer.values[1]);" in generated
    )
    assert "var color: vec3<f32> = _TestBuffer.colors[0];" in generated


def test_wgsl_codegen_lowers_structured_buffers_to_storage_bindings():
    shader = """
    shader WGSLStructuredBuffers {
        StructuredBuffer<float> values;
        RWStructuredBuffer<float> outValues;
        compute {
            void main(uint3 gid @ gl_GlobalInvocationID) {
                outValues[gid.x] = values[gid.x];
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar<storage, read> values: array<f32>;" in generated
    assert (
        "@group(0) @binding(1)\n"
        "var<storage, read_write> outValues: array<f32>;" in generated
    )
    assert "outValues[gid.x] = values[gid.x];" in generated


def test_wgsl_codegen_lowers_buffer_pointers_to_storage_bindings():
    shader = """
    shader WGSLBufferPointers {
        float readAt(buffer float* values, int index) {
            return values[index];
        }
        float readAlias(buffer float* values, int index) {
            return readAt(values, index);
        }
        void writeAt(buffer float* values, int index, float value) {
            values[index] = value;
        }
        compute {
            buffer float* inputValues;
            buffer float* outputValues;
            void main(uint3 gid @ gl_GlobalInvocationID) {
                float value = readAlias(inputValues, int(gid.x));
                writeAt(outputValues, int(gid.x), value);
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert (
        "@group(0) @binding(0)\nvar<storage, read_write> inputValues: array<f32>;"
        in generated
    )
    assert (
        "@group(0) @binding(1)\nvar<storage, read_write> outputValues: array<f32>;"
        in generated
    )
    assert (
        "fn readAt(values: ptr<storage, array<f32>, read_write>, index: i32) -> f32"
        in generated
    )
    assert "return (*values)[index];" in generated
    assert "return readAt(values, index);" in generated
    assert "(*values)[index] = value;" in generated
    assert "var value: f32 = readAlias(&inputValues, i32(gid.x));" in generated
    assert "writeAt(&outputValues, i32(gid.x), value);" in generated


def test_wgsl_codegen_emits_unique_entry_names_for_duplicate_stages():
    shader = """
    shader WGSLDuplicateComputeStages {
        compute {
            void main() {
                return;
            }
        }
        compute {
            void main() {
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "fn compute_main()" in generated
    assert "fn compute_main_1()" in generated


def test_wgsl_codegen_rejects_structured_buffers_inside_user_structs():
    shader = """
    shader WGSLStructuredBufferMember {
        struct Payload {
            StructuredBuffer<float> values;
            float factor;
        };
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="WGSL target only supports StructuredBuffer resources as module-scope storage bindings",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_structured_buffer_parameters():
    shader = """
    shader WGSLStructuredBufferParameter {
        float readFirst(StructuredBuffer<float> values) {
            return values[0];
        }
        compute {
            void main() {
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="WGSL target does not support StructuredBuffer parameters yet",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_does_not_rewrite_shadowed_cbuffer_member_identifiers():
    shader = """
    shader WGSLCBufferShadowing {
        cbuffer TestBuffer {
            float values[4];
        };
        fragment {
            vec4 main() @ gl_FragColor {
                float values = 1.0;
                return vec4(values);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var values: f32 = 1.0;" in generated
    assert "return vec4<f32>(values);" in generated
    assert "_TestBuffer.values" not in generated


def test_wgsl_codegen_allows_resource_like_user_type_names():
    shader = """
    shader WGSLResourceLikeNames {
        struct TextureInfo {
            vec4 color;
        };
        TextureInfo makeInfo() {
            TextureInfo info;
            info.color = vec4(1.0);
            return info;
        }
        fragment {
            vec4 main() @ gl_FragColor {
                TextureInfo info = makeInfo();
                return info.color;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "struct TextureInfo" in generated
    assert "fn makeInfo() -> TextureInfo" in generated
    assert "var info: TextureInfo;" in generated


def test_wgsl_aliases_format_as_noop_wgsl():
    source = "@vertex fn main() {}"

    assert format_shader_code(source, "wgsl") == source
    assert format_shader_code(source, "webgpu") == source
    assert format_shader_code(source, "shader.wgsl") == source


def test_translate_crossgl_to_wgsl(tmp_path):
    source_path = tmp_path / "shader.cgl"
    source_path.write_text(WGSL_SHADER, encoding="utf-8")

    generated = crosstl.translate(str(source_path), backend="webgpu")

    assert "@vertex" in generated
    assert "@fragment" in generated
    assert "fn fragment_main" in generated


@pytest.mark.parametrize(
    "stage",
    (
        "geometry",
        "tessellation_control",
        "tessellation_evaluation",
        "mesh",
        "task",
        "ray_generation",
    ),
)
def test_wgsl_codegen_rejects_non_webgpu_stage_targets(stage):
    ast = SimpleNamespace(functions=[], stages={})

    with pytest.raises(
        ValueError,
        match=rf"WGSL target does not support shader stage\(s\): {stage}",
    ):
        WGSLCodeGen().generate_program(ast, target_stage=stage)


def test_wgsl_codegen_rejects_do_while_statement():
    shader = """
    shader WGSLUnsupported {
        fragment {
            vec4 main() @ gl_FragColor {
                do {
                    return vec4(1.0);
                } while (false);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match="WGSL target does not support do-while statements",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


@pytest.mark.parametrize(
    ("shader", "message"),
    (
        (
            """
            shader WGSLImageResource {
                image2D colorImage;
                fragment {
                    vec4 main() @ gl_FragColor {
                        return vec4(1.0);
                    }
                }
            }
            """,
            "WGSL target does not support CrossGL resource type image2D yet; "
            "split texture/sampler/storage bindings are required",
        ),
        (
            """
            shader WGSLUnsupportedTextureCall {
                sampler2D colorTex;
                fragment {
                    vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                        return textureGather(colorTex, uv);
                    }
                }
            }
            """,
            "WGSL target does not support CrossGL texture function textureGather yet",
        ),
    ),
)
def test_wgsl_codegen_rejects_unsupported_resource_texture_constructs(shader, message):
    with pytest.raises(
        ValueError,
        match=message,
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_lowers_struct_texture_members_to_module_bindings():
    shader = """
    shader WGSLStructTextureResource {
        struct Material {
            vec3 tint;
            sampler2D colorTex;
        };
        uniform Material material;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(material.colorTex, uv) * vec4(material.tint, 1.0);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    struct_block = generated.split("};", 1)[0] + "};"
    assert (
        "struct Material {\n    tint: vec3<f32>,\n};" == struct_block.split("\n\n")[-1]
    )
    assert "    colorTex:" not in struct_block
    assert "@group(0) @binding(1)\nvar material_colorTex: texture_2d<f32>;" in generated
    assert "@group(0) @binding(2)\nvar material_colorTex_sampler: sampler;" in generated
    assert (
        "textureSample(material_colorTex, material_colorTex_sampler, uv)" in generated
    )
    assert "material.tint" in generated


def test_wgsl_codegen_lowers_struct_texture_members_in_helper_parameters():
    shader = """
    shader WGSLStructCubeTextureResource {
        struct EnvironmentData {
            samplerCube irradiance_map;
            float exposure;
        };
        vec4 sampleEnv(EnvironmentData env, vec3 direction) {
            return texture(env.irradiance_map, direction) * env.exposure;
        }
        uniform EnvironmentData environment;
        fragment {
            vec4 main(vec3 normal @ NORMAL) @ gl_FragColor {
                return sampleEnv(environment, normal);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    struct_block = generated.split("};", 1)[0] + "};"
    assert (
        "struct EnvironmentData {\n    exposure: f32,\n};"
        == struct_block.split("\n\n")[-1]
    )
    assert "    irradiance_map:" not in struct_block
    assert (
        "@group(0) @binding(1)\nvar environment_irradiance_map: " "texture_cube<f32>;"
    ) in generated
    assert (
        "@group(0) @binding(2)\nvar environment_irradiance_map_sampler: sampler;"
        in generated
    )
    assert (
        "fn sampleEnv(env: EnvironmentData, env_irradiance_map: texture_cube<f32>, "
        "env_irradiance_map_sampler: sampler, direction: vec3<f32>)"
    ) in generated
    assert (
        "textureSample(env_irradiance_map, env_irradiance_map_sampler, direction)"
    ) in generated
    assert (
        "return sampleEnv(environment, environment_irradiance_map, "
        "environment_irradiance_map_sampler, normal);"
    ) in generated
    assert "env.exposure" in generated


def test_wgsl_codegen_keeps_scalar_member_with_same_name_as_resource_member():
    shader = """
    shader WGSLStructResourceCollision {
        struct Textured {
            sampler2D colorTex;
        };
        struct Plain {
            float colorTex;
        };
        uniform Textured textured;
        uniform Plain plain;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(textured.colorTex, uv) + vec4(plain.colorTex);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var textured_colorTex: texture_2d<f32>;" in generated
    assert (
        "textureSample(textured_colorTex, textured_colorTex_sampler, uv)" in generated
    )
    assert "plain.colorTex" in generated
    assert "textureSample(plain_colorTex" not in generated


def test_wgsl_codegen_aliases_nested_resource_member_paths_from_initializer():
    shader = """
    shader WGSLStructResourceAlias {
        struct Material {
            vec3 albedo;
            sampler2D albedoMap;
        };
        struct Scene {
            Material materials[4];
        };
        struct GlobalUniforms {
            Scene scene;
        };
        uniform GlobalUniforms globals;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0, int materialIndex @ TEXCOORD1) @ gl_FragColor {
                Material material = globals.scene.materials[materialIndex];
                return texture(material.albedoMap, uv) * vec4(material.albedo, 1.0);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "albedoMap:" not in generated.split("struct Scene", 1)[0]
    assert "var globals_scene_materials_albedoMap: texture_2d<f32>;" in generated
    assert (
        "textureSample(globals_scene_materials_albedoMap, "
        "globals_scene_materials_albedoMap_sampler, uv)"
    ) in generated
    assert "material.albedo" in generated
    assert "material.albedoMap" not in generated


def test_wgsl_codegen_lowers_sampled_texture_resources_and_calls():
    shader = """
    shader WGSLTextureResource {
        sampler2D colorTex;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(colorTex, uv);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar colorTex: texture_2d<f32>;" in generated
    assert "@group(0) @binding(1)\nvar colorTex_sampler: sampler;" in generated
    assert "return textureSample(colorTex, colorTex_sampler, uv);" in generated


def test_wgsl_codegen_lowers_explicit_sampler_texture_calls():
    shader = """
    shader WGSLExplicitSamplerTexture {
        sampler2D colorTex;
        sampler linearSampler;
        fragment {
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(colorTex, linearSampler, uv);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(2)\nvar linearSampler: sampler;" in generated
    assert "return textureSample(colorTex, linearSampler, uv);" in generated


def test_wgsl_codegen_emits_stage_local_resource_declarations():
    shader = """
    shader WGSLStageLocalResources {
        fragment {
            uniform sampler2D colorTex;
            vec4 main(vec2 uv @ TEXCOORD0) @ gl_FragColor {
                return texture(colorTex, uv);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "@group(0) @binding(0)\nvar colorTex: texture_2d<f32>;" in generated
    assert "@group(0) @binding(1)\nvar colorTex_sampler: sampler;" in generated
    assert "return textureSample(colorTex, colorTex_sampler, uv);" in generated


def test_wgsl_codegen_lowers_texture_helper_parameters_and_lod_size_calls():
    shader = """
    shader WGSLTextureHelpers {
        samplerCube envMap;
        vec4 sampleEnv(samplerCube tex, vec3 direction) {
            uint2 size = textureSize(tex, 0);
            return textureLod(tex, direction, 1.0);
        }
        fragment {
            vec4 main(vec3 normal @ NORMAL) @ gl_FragColor {
                return sampleEnv(envMap, normal);
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "var envMap: texture_cube<f32>;" in generated
    assert "var envMap_sampler: sampler;" in generated
    assert (
        "fn sampleEnv(tex: texture_cube<f32>, tex_sampler: sampler, "
        "direction: vec3<f32>) -> vec4<f32>"
    ) in generated
    assert "var size: vec2<u32> = textureDimensions(tex, 0);" in generated
    assert "textureSampleLevel(tex, tex_sampler, direction, 1.0)" in generated
    assert "return sampleEnv(envMap, envMap_sampler, normal);" in generated


def test_wgsl_codegen_lowers_compute_barrier_to_workgroup_barrier():
    shader = """
    shader WGSLBarrier {
        compute {
            layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in;
            void main() {
                barrier();
                return;
            }
        }
    }
    """

    generated = WGSLCodeGen().generate(parse_shader(shader))

    assert "workgroupBarrier();" in generated
    assert "barrier();" not in generated


def test_wgsl_codegen_rejects_barrier_outside_compute_stages():
    shader = """
    shader WGSLFragmentBarrier {
        fragment {
            vec4 main() @ gl_FragColor {
                barrier();
                return vec4(1.0);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=r"WGSL target only supports barrier\(\) inside compute stages",
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_direct_builtin_references_in_helpers():
    shader = """
    shader WGSLHelperBuiltin {
        uint helper() {
            return gl_GlobalInvocationID.x;
        }
        compute {
            void main() {
                uint lane = helper();
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support direct builtin identifier\\(s\\) "
            "in helper function helper: gl_GlobalInvocationID"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_compute_builtin_references_in_fragment_stage():
    shader = """
    shader WGSLFragmentComputeBuiltin {
        fragment {
            vec4 main() @ gl_FragColor {
                uint lane = gl_GlobalInvocationID.x;
                return vec4(1.0);
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support implicit builtin identifier\\(s\\) "
            "in fragment stage: gl_GlobalInvocationID"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_implicit_builtin_parameter_name_collision():
    shader = """
    shader WGSLBuiltinNameCollision {
        compute {
            void main(uint3 global_invocation_id) {
                uint lane = gl_GlobalInvocationID.x;
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target cannot inject builtin global_invocation_id because "
            "an entry parameter already uses that name without "
            "@builtin\\(global_invocation_id\\)"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))


def test_wgsl_codegen_rejects_barriers_in_helpers_with_specific_diagnostic():
    shader = """
    shader WGSLHelperBarrier {
        void sync() {
            barrier();
            return;
        }
        compute {
            void main() {
                sync();
                return;
            }
        }
    }
    """

    with pytest.raises(
        ValueError,
        match=(
            "WGSL target does not support barrier\\(\\) inside helper function "
            "sync yet"
        ),
    ):
        WGSLCodeGen().generate(parse_shader(shader))
