name: Auto-Assign Issues

on:
  issue_comment:
    types: [created]

jobs:
  assign_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Check if the comment is requesting assignment
      if: github.event.comment.body == 'assign to me'
      run: |
        gh api \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d '{"assignees":["${{ github.event.comment.user.login }}"]}'
