name: Shader Language Feature Discovery

on:
  schedule:
    # Run biweekly at midnight UTC on Mondays
    - cron: "0 0 * * 1/2"
  pull_request: # remove before merging
    branches:
      - main
  workflow_dispatch: # Allow manual triggering
    inputs:
      languages:
        description: "Comma-separated list of languages to analyze (leave empty for all)"
        required: false
        default: ""
      force_refresh:
        description: "Force refresh cached documentation"
        required: false
        type: boolean
        default: false

env:
  CACHE_VERSION: 1 # Increment to invalidate caches

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up matrix
        id: set-matrix
        run: |
          LANGUAGES="${{ github.event.inputs.languages }}"
          if [ -z "$LANGUAGES" ]; then
            LANGUAGES="metal,directx,opengl,vulkan,slang,mojo"
          fi
          JSON_ARRAY=$(echo "$LANGUAGES" | tr ',' '\n' | jq -R . | jq -s -c .)
          echo "matrix={\"language\":$JSON_ARRAY}" >> $GITHUB_OUTPUT

  analyze-documentation:
    needs: prepare
    runs-on: ubuntu-latest-64-cores # Using larger runner for performance
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          pip install PyGithub beautifulsoup4 selenium webdriver-manager lxml html5lib markdownify requests aiohttp nltk spacy 
          python -m spacy download en_core_web_sm
          python -m nltk.downloader punkt wordnet stopwords

      - name: Cache documentation
        id: cache-docs
        uses: actions/cache@v4
        with:
          path: ./.cache/docs/${{ matrix.language }}
          key: docs-${{ matrix.language }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.github/scripts/docs_crawler.py') }}
          restore-keys: |
            docs-${{ matrix.language }}-${{ env.CACHE_VERSION }}-

      - name: Download documentation
        if: steps.cache-docs.outputs.cache-hit != 'true' || github.event.inputs.force_refresh == 'true'
        run: |
          python .github/scripts/docs_crawler.py --language ${{ matrix.language }} --download-only

      - name: Analyze documentation
        run: |
          python .github/scripts/docs_crawler.py --language ${{ matrix.language }} --analyze-only

      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language }}-analysis
          path: ./.cache/analysis/${{ matrix.language }}.json
          retention-days: 1

  generate-issues:
    needs: analyze-documentation
    runs-on: ubuntu-latest-16-cores
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          pip install PyGithub jinja2 pyyaml rich tqdm

      - name: Download all analysis results
        uses: actions/download-artifact@v4
        with:
          path: ./.cache/analysis/

      - name: Create GitHub Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/issue_generator.py

      - name: Generate Report
        run: |
          python .github/scripts/generate_report.py

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: implementation-status-report
          path: ./.cache/reports/
          retention-days: 30
