name: PR Merge Main
on:
  pull_request:

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Merge main into PR branch
        run: |
          git fetch origin main
          branch_name=${{ github.head_ref || github.ref_name }}
          git checkout $branch_name
          git merge origin/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: |
          branch_name=${{ github.head_ref || github.ref_name }}
          git push origin $branch_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
